// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: rpc/snailjob.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnaryRequest_UnaryRequest_FullMethodName = "/UnaryRequest/unaryRequest"
)

// UnaryRequestClient is the client API for UnaryRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnaryRequestClient interface {
	UnaryRequest(ctx context.Context, in *GrpcSnailJobRequest, opts ...grpc.CallOption) (*GrpcResult, error)
}

type unaryRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewUnaryRequestClient(cc grpc.ClientConnInterface) UnaryRequestClient {
	return &unaryRequestClient{cc}
}

func (c *unaryRequestClient) UnaryRequest(ctx context.Context, in *GrpcSnailJobRequest, opts ...grpc.CallOption) (*GrpcResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcResult)
	err := c.cc.Invoke(ctx, UnaryRequest_UnaryRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryRequestServer is the server API for UnaryRequest service.
// All implementations must embed UnimplementedUnaryRequestServer
// for forward compatibility.
type UnaryRequestServer interface {
	UnaryRequest(context.Context, *GrpcSnailJobRequest) (*GrpcResult, error)
	mustEmbedUnimplementedUnaryRequestServer()
}

// UnimplementedUnaryRequestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnaryRequestServer struct{}

func (UnimplementedUnaryRequestServer) UnaryRequest(context.Context, *GrpcSnailJobRequest) (*GrpcResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRequest not implemented")
}
func (UnimplementedUnaryRequestServer) mustEmbedUnimplementedUnaryRequestServer() {}
func (UnimplementedUnaryRequestServer) testEmbeddedByValue()                      {}

// UnsafeUnaryRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnaryRequestServer will
// result in compilation errors.
type UnsafeUnaryRequestServer interface {
	mustEmbedUnimplementedUnaryRequestServer()
}

func RegisterUnaryRequestServer(s grpc.ServiceRegistrar, srv UnaryRequestServer) {
	// If the following call pancis, it indicates UnimplementedUnaryRequestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnaryRequest_ServiceDesc, srv)
}

func _UnaryRequest_UnaryRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcSnailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryRequestServer).UnaryRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryRequest_UnaryRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryRequestServer).UnaryRequest(ctx, req.(*GrpcSnailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnaryRequest_ServiceDesc is the grpc.ServiceDesc for UnaryRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnaryRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UnaryRequest",
	HandlerType: (*UnaryRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "unaryRequest",
			Handler:    _UnaryRequest_UnaryRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/snailjob.proto",
}
