// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: rpc/snailjob.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     string            `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers map[string]string `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_rpc_snailjob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_snailjob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_rpc_snailjob_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Metadata) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GrpcSnailJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId    int64     `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Body     string    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GrpcSnailJobRequest) Reset() {
	*x = GrpcSnailJobRequest{}
	mi := &file_rpc_snailjob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcSnailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSnailJobRequest) ProtoMessage() {}

func (x *GrpcSnailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_snailjob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSnailJobRequest.ProtoReflect.Descriptor instead.
func (*GrpcSnailJobRequest) Descriptor() ([]byte, []int) {
	return file_rpc_snailjob_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcSnailJobRequest) GetReqId() int64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *GrpcSnailJobRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcSnailJobRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GrpcResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId   int64  `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Status  int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GrpcResult) Reset() {
	*x = GrpcResult{}
	mi := &file_rpc_snailjob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcResult) ProtoMessage() {}

func (x *GrpcResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_snailjob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcResult.ProtoReflect.Descriptor instead.
func (*GrpcResult) Descriptor() ([]byte, []int) {
	return file_rpc_snailjob_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcResult) GetReqId() int64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *GrpcResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GrpcResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GrpcResult) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_rpc_snailjob_proto protoreflect.FileDescriptor

var file_rpc_snailjob_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6e, 0x61, 0x69, 0x6c, 0x6a, 0x6f, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x30, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x66, 0x0a, 0x13, 0x47, 0x72, 0x70, 0x63, 0x53, 0x6e, 0x61, 0x69, 0x6c, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x68, 0x0a, 0x0a, 0x47, 0x72, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x41, 0x0a, 0x0c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0c, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x53, 0x6e, 0x61, 0x69, 0x6c, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x6e,
	0x61, 0x69, 0x6c, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x73, 0x6e, 0x61, 0x69, 0x6c, 0x2d, 0x6a, 0x6f,
	0x62, 0x2f, 0x73, 0x6e, 0x61, 0x69, 0x6c, 0x2d, 0x6a, 0x6f, 0x62, 0x2d, 0x67, 0x6f, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_snailjob_proto_rawDescOnce sync.Once
	file_rpc_snailjob_proto_rawDescData = file_rpc_snailjob_proto_rawDesc
)

func file_rpc_snailjob_proto_rawDescGZIP() []byte {
	file_rpc_snailjob_proto_rawDescOnce.Do(func() {
		file_rpc_snailjob_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_snailjob_proto_rawDescData)
	})
	return file_rpc_snailjob_proto_rawDescData
}

var file_rpc_snailjob_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_snailjob_proto_goTypes = []any{
	(*Metadata)(nil),            // 0: Metadata
	(*GrpcSnailJobRequest)(nil), // 1: GrpcSnailJobRequest
	(*GrpcResult)(nil),          // 2: GrpcResult
	nil,                         // 3: Metadata.HeadersEntry
}
var file_rpc_snailjob_proto_depIdxs = []int32{
	3, // 0: Metadata.headers:type_name -> Metadata.HeadersEntry
	0, // 1: GrpcSnailJobRequest.metadata:type_name -> Metadata
	1, // 2: UnaryRequest.unaryRequest:input_type -> GrpcSnailJobRequest
	2, // 3: UnaryRequest.unaryRequest:output_type -> GrpcResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_snailjob_proto_init() }
func file_rpc_snailjob_proto_init() {
	if File_rpc_snailjob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_snailjob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_snailjob_proto_goTypes,
		DependencyIndexes: file_rpc_snailjob_proto_depIdxs,
		MessageInfos:      file_rpc_snailjob_proto_msgTypes,
	}.Build()
	File_rpc_snailjob_proto = out.File
	file_rpc_snailjob_proto_rawDesc = nil
	file_rpc_snailjob_proto_goTypes = nil
	file_rpc_snailjob_proto_depIdxs = nil
}
